name: Deploy GitHub Page

on:
  push:
    branches: [ production ]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Setup Environment
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
